# Site
title: FACTLAB
subtitle: A Lab Space

# URL
url: http://fact.alab.space
baseurl: /
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4444

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      cover: "/assets/posts/ob_ject-and-ob_serve/cover01.jpg"

# Data
social:
  facebook_url: "https://www.facebook.com/thiago.hersan"
  twitter_url: "https://www.twitter.com/thiagohersan"
  twitter_user: "@thiagohersan"
